// @ts-nocheck
// This file was generated by specta. Do not edit.
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  Validate that `path` is a git repository and return its metadata. */
	openRepository: (path: string) => typedError<RepoInfo, AppError>(__TAURI_INVOKE("open_repository", { path })),
	/**  Return all recorded git CLI invocations. */
	getCommandLog: () => __TAURI_INVOKE<CommandEntry[]>("get_command_log"),
	/**  Return the name of the current branch for the repository at `repo_path`. */
	getCurrentBranch: (repoPath: string) => typedError<string, AppError>(__TAURI_INVOKE("get_current_branch", { repoPath })),
	/**  Return the commit log for the current branch, most recent first. */
	getCommitLog: (repoPath: string, limit: number) => typedError<CommitInfo[], AppError>(__TAURI_INVOKE("get_commit_log", { repoPath, limit })),
	/**  Return all local branches, ordered by most recent commit date. */
	listBranches: (repoPath: string) => typedError<BranchInfo[], AppError>(__TAURI_INVOKE("list_branches", { repoPath })),
	/**  Switch to the given branch. */
	switchBranch: (repoPath: string, branchName: string) => typedError<null, AppError>(__TAURI_INVOKE("switch_branch", { repoPath, branchName })),
	/**  Create a new branch from HEAD and switch to it. */
	createBranch: (repoPath: string, branchName: string) => typedError<null, AppError>(__TAURI_INVOKE("create_branch", { repoPath, branchName })),
	/**  Return the staged and unstaged file changes for the repository. */
	getStatus: (repoPath: string) => typedError<RepoStatus, AppError>(__TAURI_INVOKE("get_status", { repoPath })),
	/**  Create a commit from the currently staged changes. */
	commit: (repoPath: string, summary: string, description: string) => typedError<null, AppError>(__TAURI_INVOKE("commit", { repoPath, summary, description })),
	/**  Stage the given files. */
	stageFiles: (repoPath: string, paths: string[]) => typedError<null, AppError>(__TAURI_INVOKE("stage_files", { repoPath, paths })),
	/**  Unstage the given files. */
	unstageFiles: (repoPath: string, paths: string[]) => typedError<null, AppError>(__TAURI_INVOKE("unstage_files", { repoPath, paths })),
	/**  Read the contents of a file in the repository working tree. */
	readFileContents: (repoPath: string, relativePath: string) => typedError<string, AppError>(__TAURI_INVOKE("read_file_contents", { repoPath, relativePath })),
	/**  Return the diff for a single file, either staged or unstaged. */
	getFileDiff: (repoPath: string, relativePath: string, area: DiffArea) => typedError<FileDiff, AppError>(__TAURI_INVOKE("get_file_diff", { repoPath, relativePath, area })),
};

/* Types */
/**  Centralized error type for the application. */
export type AppError = ({ Git: string }) & { Io?: never; Other?: never } | ({ Io: string }) & { Git?: never; Other?: never } | ({ Other: string }) & { Git?: never; Io?: never };

/**  A branch in the repository. */
export type BranchInfo = {
	/**  Branch name (e.g. "main"). */
	name: string,
	/**  Whether this is the currently checked-out branch. */
	is_current: boolean,
	/**  ISO 8601 timestamp of the most recent commit on this branch. */
	last_commit_date: string,
};

/**  A single recorded git CLI invocation. */
export type CommandEntry = {
	timestamp: string,
	command: string,
	cwd: string,
	exit_code: number,
	stdout: string,
	stderr: string,
};

/**  A single commit in the repository history. */
export type CommitInfo = {
	/**  Full commit hash. */
	hash: string,
	/**  Short (abbreviated) commit hash. */
	short_hash: string,
	/**  First line of the commit message. */
	summary: string,
	/**  Author name. */
	author: string,
	/**  ISO 8601 timestamp. */
	timestamp: string,
};

/**  Whether to diff staged (cached) or unstaged (worktree) changes. */
export type DiffArea = "Staged" | "Unstaged";

/**  A contiguous hunk of changes. */
export type DiffHunk = {
	/**  The hunk header (e.g. "@@ -1,3 +1,5 @@"). */
	header: string,
	/**  Starting line in the old file. */
	old_start: number,
	/**  Starting line in the new file. */
	new_start: number,
	/**  Lines in this hunk. */
	lines: DiffLine[],
};

/**  A single line within a diff hunk. */
export type DiffLine = {
	/**  The kind of change. */
	kind: DiffLineKind,
	/**  The line content (without the leading +/-/space). */
	content: string,
	/**  Line number in the old (a) side, if applicable. */
	old_lineno: number | null,
	/**  Line number in the new (b) side, if applicable. */
	new_lineno: number | null,
};

/**  The type of a line in a diff hunk. */
export type DiffLineKind = "Context" | "Addition" | "Deletion";

/**  The complete diff output for a single file. */
export type FileDiff = {
	/**  The relative path of the file. */
	path: string,
	/**  The hunks that make up this diff. */
	hunks: DiffHunk[],
};

/**  The kind of change a file has undergone. */
export type FileStatus = "Added" | "Modified" | "Deleted" | "Renamed" | "Copied" | "Untracked" | "Unknown";

/**  Basic metadata about an opened repository. */
export type RepoInfo = {
	/**  Human-readable name (typically the folder name). */
	name: string,
	/**  Absolute path to the repository root. */
	path: string,
};

/**  The full working-tree status of a repository. */
export type RepoStatus = {
	/**  Files with staged (index) changes. */
	staged: StatusEntry[],
	/**  Files with unstaged (worktree) changes. */
	unstaged: StatusEntry[],
};

/**  A changed file in the working tree or index. */
export type StatusEntry = {
	/**  Relative path of the file. */
	path: string,
	/**  Kind of change. */
	status: FileStatus,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

