// @ts-nocheck
// This file was generated by specta. Do not edit.
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  Validate that `path` is a git repository and return its metadata. */
	openRepository: (path: string) => typedError<RepoInfo, AppError>(__TAURI_INVOKE("open_repository", { path })),
	/**  Return all recorded git CLI invocations. */
	getCommandLog: () => __TAURI_INVOKE<CommandEntry[]>("get_command_log"),
	/**  Return the name of the current branch for the repository at `repo_path`. */
	getCurrentBranch: (repoPath: string) => typedError<string, AppError>(__TAURI_INVOKE("get_current_branch", { repoPath })),
	/**  Return the commit log for the current branch, most recent first. */
	getCommitLog: (repoPath: string, limit: number) => typedError<CommitInfo[], AppError>(__TAURI_INVOKE("get_commit_log", { repoPath, limit })),
	/**  Return diffs for all files changed in a specific commit. */
	getCommitDiff: (repoPath: string, hash: string) => typedError<FileDiff[], AppError>(__TAURI_INVOKE("get_commit_diff", { repoPath, hash })),
	/**  Return the diff for a single file within a specific commit. */
	getCommitFileDiff: (repoPath: string, hash: string, filePath: string) => typedError<FileDiff, AppError>(__TAURI_INVOKE("get_commit_file_diff", { repoPath, hash, filePath })),
	/**  Return the contents of a file at a specific commit revision. */
	getFileAtCommit: (repoPath: string, hash: string, filePath: string) => typedError<string, AppError>(__TAURI_INVOKE("get_file_at_commit", { repoPath, hash, filePath })),
	/**  Return the list of files changed in a specific commit. */
	listCommitFiles: (repoPath: string, hash: string) => typedError<StatusEntry[], AppError>(__TAURI_INVOKE("list_commit_files", { repoPath, hash })),
	/**  Return all local branches, ordered by most recent commit date. */
	listBranches: (repoPath: string) => typedError<BranchInfo[], AppError>(__TAURI_INVOKE("list_branches", { repoPath })),
	/**  Switch to the given branch. */
	switchBranch: (repoPath: string, branchName: string) => typedError<null, AppError>(__TAURI_INVOKE("switch_branch", { repoPath, branchName })),
	/**  Create a new branch from HEAD and switch to it. */
	createBranch: (repoPath: string, branchName: string) => typedError<null, AppError>(__TAURI_INVOKE("create_branch", { repoPath, branchName })),
	/**  Return the branch graph data for visualization. */
	getBranchGraph: (repoPath: string, branches: string[], remote: string | null, maxCommits: number | null) => typedError<BranchGraphData, AppError>(__TAURI_INVOKE("get_branch_graph", { repoPath, branches, remote, maxCommits })),
	/**  Return the staged and unstaged file changes for the repository. */
	getStatus: (repoPath: string) => typedError<RepoStatus, AppError>(__TAURI_INVOKE("get_status", { repoPath })),
	/**  Create a commit from the currently staged changes. */
	commit: (repoPath: string, summary: string, description: string) => typedError<null, AppError>(__TAURI_INVOKE("commit", { repoPath, summary, description })),
	/**  Stage the given files. */
	stageFiles: (repoPath: string, paths: string[]) => typedError<null, AppError>(__TAURI_INVOKE("stage_files", { repoPath, paths })),
	/**  Stage specific lines from a file's unstaged diff. */
	stageLines: (repoPath: string, filePath: string, diff: FileDiff, selections: LineSelection[]) => typedError<null, AppError>(__TAURI_INVOKE("stage_lines", { repoPath, filePath, diff, selections })),
	/**  Unstage the given files. */
	unstageFiles: (repoPath: string, paths: string[]) => typedError<null, AppError>(__TAURI_INVOKE("unstage_files", { repoPath, paths })),
	/**  Unstage specific lines from a file's staged diff. */
	unstageLines: (repoPath: string, filePath: string, diff: FileDiff, selections: LineSelection[]) => typedError<null, AppError>(__TAURI_INVOKE("unstage_lines", { repoPath, filePath, diff, selections })),
	/**  Read the contents of a file in the repository working tree. */
	readFileContents: (repoPath: string, relativePath: string) => typedError<string, AppError>(__TAURI_INVOKE("read_file_contents", { repoPath, relativePath })),
	/**  Return the diff for a single file, either staged or unstaged. */
	getFileDiff: (repoPath: string, relativePath: string, area: DiffArea) => typedError<FileDiff, AppError>(__TAURI_INVOKE("get_file_diff", { repoPath, relativePath, area })),
	/**  Return all configured remotes for the repository. */
	listRemotes: (repoPath: string) => typedError<RemoteInfo[], AppError>(__TAURI_INVOKE("list_remotes", { repoPath })),
	/**  Return the ahead/behind status of the current branch relative to its upstream. */
	getTrackingStatus: (repoPath: string) => typedError<{
	/**  Number of commits the local branch is ahead of upstream. */
	ahead: number,
	/**  Number of commits the local branch is behind upstream. */
	behind: number,
	/**  The upstream reference (e.g. "origin/main"). */
	upstream: string,
} | null, AppError>(__TAURI_INVOKE("get_tracking_status", { repoPath })),
	/**  Push the current branch to the specified remote. */
	push: (repoPath: string, remote: string) => typedError<null, AppError>(__TAURI_INVOKE("push", { repoPath, remote })),
	/**  Publish the current branch to the specified remote (push with --set-upstream). */
	publishBranch: (repoPath: string, remote: string) => typedError<null, AppError>(__TAURI_INVOKE("publish_branch", { repoPath, remote })),
	/**  Pull from the specified remote into the current branch. */
	pull: (repoPath: string, remote: string) => typedError<null, AppError>(__TAURI_INVOKE("pull", { repoPath, remote })),
	/**  Fetch from the specified remote. */
	fetch: (repoPath: string, remote: string) => typedError<null, AppError>(__TAURI_INVOKE("fetch", { repoPath, remote })),
	/**  Return the persisted app state (repos, active tab, etc.). */
	getAppState: () => __TAURI_INVOKE<AppState>("get_app_state"),
	/**  Save the current app state to disk. */
	saveAppState: (state: AppState) => __TAURI_INVOKE<void>("save_app_state", { state }),
};

/* Types */
/**  Centralized error type for the application. */
export type AppError = ({ Git: string }) & { Io?: never; Other?: never } | ({ Io: string }) & { Git?: never; Other?: never } | ({ Other: string }) & { Git?: never; Io?: never };

/**  Persisted application state (survives across app restarts). */
export type AppState = {
	/**  Paths of repositories that were open. */
	open_repos?: string[],
	/**  Index of the active tab. */
	active_index?: number,
};

/**  Data for rendering a branch graph. */
export type BranchGraphData = {
	/**  Commits in topological order (most recent first). */
	commits: GraphCommit[],
	/**  Names of the branches included in this graph. */
	branches: string[],
	/**  Commit hashes that exist only locally (not pushed to the selected remote). */
	local_only_commits: string[],
};

/**  A branch in the repository. */
export type BranchInfo = {
	/**  Branch name (e.g. "main"). */
	name: string,
	/**  Whether this is the currently checked-out branch. */
	is_current: boolean,
	/**  ISO 8601 timestamp of the most recent commit on this branch. */
	last_commit_date: string,
};

/**  How far ahead/behind the local branch is relative to its upstream. */
export type BranchTrackingStatus = {
	/**  Number of commits the local branch is ahead of upstream. */
	ahead: number,
	/**  Number of commits the local branch is behind upstream. */
	behind: number,
	/**  The upstream reference (e.g. "origin/main"). */
	upstream: string,
};

/**  A single recorded git CLI invocation. */
export type CommandEntry = {
	timestamp: string,
	command: string,
	cwd: string,
	exit_code: number,
	stdout: string,
	stderr: string,
	/**  How long the command took to execute, in milliseconds. */
	elapsed_ms: number,
	/**  Whether this command was a background/periodic operation (e.g. polling). */
	is_background: boolean,
};

/**  A single commit in the repository history. */
export type CommitInfo = {
	/**  Full commit hash. */
	hash: string,
	/**  Short (abbreviated) commit hash. */
	short_hash: string,
	/**  First line of the commit message. */
	summary: string,
	/**  Author name. */
	author: string,
	/**  ISO 8601 timestamp. */
	timestamp: string,
};

/**  Whether to diff staged (cached) or unstaged (worktree) changes. */
export type DiffArea = "Staged" | "Unstaged";

/**  A contiguous hunk of changes. */
export type DiffHunk = {
	/**  The hunk header (e.g. "@@ -1,3 +1,5 @@"). */
	header: string,
	/**  Starting line in the old file. */
	old_start: number,
	/**  Starting line in the new file. */
	new_start: number,
	/**  Lines in this hunk. */
	lines: DiffLine[],
};

/**  A single line within a diff hunk. */
export type DiffLine = {
	/**  The kind of change. */
	kind: DiffLineKind,
	/**  The line content (without the leading +/-/space). */
	content: string,
	/**  Line number in the old (a) side, if applicable. */
	old_lineno: number | null,
	/**  Line number in the new (b) side, if applicable. */
	new_lineno: number | null,
};

/**  The type of a line in a diff hunk. */
export type DiffLineKind = "Context" | "Addition" | "Deletion";

/**  The complete diff output for a single file. */
export type FileDiff = {
	/**  The relative path of the file. */
	path: string,
	/**  The hunks that make up this diff. */
	hunks: DiffHunk[],
};

/**  The kind of change a file has undergone. */
export type FileStatus = "Added" | "Modified" | "Deleted" | "Renamed" | "Copied" | "Untracked" | "Unknown";

/**  A commit node in the branch graph visualization. */
export type GraphCommit = {
	/**  Full commit hash. */
	hash: string,
	/**  Short (abbreviated) commit hash. */
	short_hash: string,
	/**  First line of the commit message. */
	summary: string,
	/**  Author name. */
	author: string,
	/**  ISO 8601 timestamp. */
	timestamp: string,
	/**  Full hashes of parent commits. */
	parents: string[],
	/**  Branch/ref names pointing to this commit (e.g. "main", "origin/main"). */
	refs: string[],
};

/**
 *  A selection of lines within a diff to stage/unstage.
 *  Each entry is (hunk_index, line_index_within_hunk).
 */
export type LineSelection = {
	hunk_index: number,
	line_index: number,
};

/**  A configured remote for the repository. */
export type RemoteInfo = {
	/**  Remote name (e.g. "origin"). */
	name: string,
	/**  Remote URL. */
	url: string,
};

/**  Basic metadata about an opened repository. */
export type RepoInfo = {
	/**  Human-readable name (typically the folder name). */
	name: string,
	/**  Absolute path to the repository root. */
	path: string,
};

/**  The full working-tree status of a repository. */
export type RepoStatus = {
	/**  Files with staged (index) changes. */
	staged: StatusEntry[],
	/**  Files with unstaged (worktree) changes. */
	unstaged: StatusEntry[],
};

/**  A changed file in the working tree or index. */
export type StatusEntry = {
	/**  Relative path of the file. */
	path: string,
	/**  Kind of change. */
	status: FileStatus,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

