// @ts-nocheck
// This file was generated by specta. Do not edit.
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  Validate that `path` is a git repository and return its metadata. */
	openRepository: (path: string) => typedError<RepoInfo, AppError>(__TAURI_INVOKE("open_repository", { path })),
	/**  Initialize a new git repository in `parent_folder/name`. */
	initRepository: (parentFolder: string, name: string) => typedError<RepoInfo, AppError>(__TAURI_INVOKE("init_repository", { parentFolder, name })),
	/**  Clone a remote repository into `parent_folder`. */
	cloneRepository: (url: string, parentFolder: string) => typedError<RepoInfo, AppError>(__TAURI_INVOKE("clone_repository", { url, parentFolder })),
	/**  Check whether a directory path exists on disk. */
	checkPathExists: (path: string) => __TAURI_INVOKE<boolean>("check_path_exists", { path }),
	/**
	 *  Validate that `parent_folder/name` is a usable target for a new repository.
	 *  Returns Ok if the parent exists and the target either doesn't exist or is an
	 *  empty directory.  Returns a descriptive error otherwise.
	 */
	validateRepoPath: (parentFolder: string, name: string) => typedError<null, AppError>(__TAURI_INVOKE("validate_repo_path", { parentFolder, name })),
	/**  Return all recorded git CLI invocations. */
	getCommandLog: () => typedError<CommandEntry[], AppError>(__TAURI_INVOKE("get_command_log")),
	/**  Return the name of the current branch for the repository at `repo_path`. */
	getCurrentBranch: (repoPath: string) => typedError<string, AppError>(__TAURI_INVOKE("get_current_branch", { repoPath })),
	/**  Return the full HEAD state: current branch, and whether we are browsing history. */
	getHeadState: (repoPath: string) => typedError<HeadState, AppError>(__TAURI_INVOKE("get_head_state", { repoPath })),
	/**  Checkout a specific commit by hash (enters history-browsing mode). */
	checkoutCommit: (repoPath: string, hash: string) => typedError<null, AppError>(__TAURI_INVOKE("checkout_commit", { repoPath, hash })),
	/**  Return the commit log for the current branch, most recent first. */
	getCommitLog: (repoPath: string, limit: number) => typedError<CommitInfo[], AppError>(__TAURI_INVOKE("get_commit_log", { repoPath, limit })),
	/**  Return diffs for all files changed in a specific commit. */
	getCommitDiff: (repoPath: string, hash: string) => typedError<FileDiff[], AppError>(__TAURI_INVOKE("get_commit_diff", { repoPath, hash })),
	/**  Return the diff for a single file within a specific commit. */
	getCommitFileDiff: (repoPath: string, hash: string, filePath: string) => typedError<FileDiff, AppError>(__TAURI_INVOKE("get_commit_file_diff", { repoPath, hash, filePath })),
	/**  Return the contents of a file at a specific commit revision. */
	getFileAtCommit: (repoPath: string, hash: string, filePath: string) => typedError<string, AppError>(__TAURI_INVOKE("get_file_at_commit", { repoPath, hash, filePath })),
	/**  Return the list of files changed in a specific commit. */
	listCommitFiles: (repoPath: string, hash: string) => typedError<StatusEntry[], AppError>(__TAURI_INVOKE("list_commit_files", { repoPath, hash })),
	/**  Return all local branches, ordered by most recent commit date. */
	listBranches: (repoPath: string) => typedError<BranchInfo[], AppError>(__TAURI_INVOKE("list_branches", { repoPath })),
	/**  Return remote-only branches (those with no local tracking branch). */
	listRemoteBranches: (repoPath: string) => typedError<RemoteBranchInfo[], AppError>(__TAURI_INVOKE("list_remote_branches", { repoPath })),
	/**  Switch to the given branch. */
	switchBranch: (repoPath: string, branchName: string) => typedError<null, AppError>(__TAURI_INVOKE("switch_branch", { repoPath, branchName })),
	/**  Create a new branch from HEAD and switch to it. */
	createBranch: (repoPath: string, branchName: string) => typedError<null, AppError>(__TAURI_INVOKE("create_branch", { repoPath, branchName })),
	/**  Cherry-pick selected commits onto an existing or newly-created target branch. */
	cherryPickCommits: (repoPath: string, hashes: string[], targetBranch: string, createBranch: boolean) => typedError<null, AppError>(__TAURI_INVOKE("cherry_pick_commits", { repoPath, hashes, targetBranch, createBranch })),
	/**  Delete a local branch. If `force` is true, force-delete even if unmerged. */
	deleteBranch: (repoPath: string, branchName: string, force: boolean) => typedError<null, AppError>(__TAURI_INVOKE("delete_branch", { repoPath, branchName, force })),
	/**  Delete a branch on the remote. */
	deleteRemoteBranch: (repoPath: string, remote: string, branchName: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_remote_branch", { repoPath, remote, branchName })),
	/**  Return information needed to decide how to handle deletion of a branch. */
	getBranchDeleteInfo: (repoPath: string, branchName: string) => typedError<BranchDeleteInfo, AppError>(__TAURI_INVOKE("get_branch_delete_info", { repoPath, branchName })),
	/**  Return the branch graph data for visualization. */
	getBranchGraph: (repoPath: string, branches: string[], remote: string | null, maxCommits: number | null) => typedError<BranchGraphData, AppError>(__TAURI_INVOKE("get_branch_graph", { repoPath, branches, remote, maxCommits })),
	/**  Return the staged and unstaged file changes for the repository. */
	getStatus: (repoPath: string) => typedError<RepoStatus, AppError>(__TAURI_INVOKE("get_status", { repoPath })),
	/**  Create a commit from the currently staged changes. */
	commit: (repoPath: string, summary: string, description: string, allowEmpty: boolean) => typedError<null, AppError>(__TAURI_INVOKE("commit", { repoPath, summary, description, allowEmpty })),
	/**  Undo the latest unpushed commit and restore its message. */
	undoLastCommit: (repoPath: string) => typedError<RestoredCommitMessage, AppError>(__TAURI_INVOKE("undo_last_commit", { repoPath })),
	/**  Stage the given files. */
	stageFiles: (repoPath: string, paths: string[]) => typedError<null, AppError>(__TAURI_INVOKE("stage_files", { repoPath, paths })),
	/**  Stage specific lines from a file's unstaged diff. */
	stageLines: (repoPath: string, filePath: string, diff: FileDiff, selections: LineSelection[]) => typedError<null, AppError>(__TAURI_INVOKE("stage_lines", { repoPath, filePath, diff, selections })),
	/**  Unstage the given files. */
	unstageFiles: (repoPath: string, paths: string[]) => typedError<null, AppError>(__TAURI_INVOKE("unstage_files", { repoPath, paths })),
	/**  Unstage specific lines from a file's staged diff. */
	unstageLines: (repoPath: string, filePath: string, diff: FileDiff, selections: LineSelection[]) => typedError<null, AppError>(__TAURI_INVOKE("unstage_lines", { repoPath, filePath, diff, selections })),
	/**  Discard unstaged changes for the given files. */
	discardUnstagedFiles: (repoPath: string, paths: string[]) => typedError<null, AppError>(__TAURI_INVOKE("discard_unstaged_files", { repoPath, paths })),
	/**  Discard staged changes for the given files. */
	discardStagedFiles: (repoPath: string, paths: string[]) => typedError<null, AppError>(__TAURI_INVOKE("discard_staged_files", { repoPath, paths })),
	/**  Discard specific lines from a file's diff. */
	discardLines: (repoPath: string, filePath: string, diff: FileDiff, selections: LineSelection[], area: DiffArea) => typedError<null, AppError>(__TAURI_INVOKE("discard_lines", { repoPath, filePath, diff, selections, area })),
	/**  Read the contents of a file in the repository working tree. */
	readFileContents: (repoPath: string, relativePath: string) => typedError<string, AppError>(__TAURI_INVOKE("read_file_contents", { repoPath, relativePath })),
	/**  Return the diff for a single file, either staged or unstaged. */
	getFileDiff: (repoPath: string, relativePath: string, area: DiffArea) => typedError<FileDiff, AppError>(__TAURI_INVOKE("get_file_diff", { repoPath, relativePath, area })),
	/**  Return per-file addition/deletion statistics for staged or unstaged changes. */
	getDiffStats: (repoPath: string, area: DiffArea) => typedError<FileStats[], AppError>(__TAURI_INVOKE("get_diff_stats", { repoPath, area })),
	/**  Return per-file addition/deletion statistics for a specific commit. */
	getCommitFileStats: (repoPath: string, hash: string) => typedError<FileStats[], AppError>(__TAURI_INVOKE("get_commit_file_stats", { repoPath, hash })),
	/**  Return all configured remotes for the repository. */
	listRemotes: (repoPath: string) => typedError<RemoteInfo[], AppError>(__TAURI_INVOKE("list_remotes", { repoPath })),
	/**  Return the ahead/behind status of the current branch relative to its upstream. */
	getTrackingStatus: (repoPath: string) => typedError<{
	/**  Number of commits the local branch is ahead of upstream. */
	ahead: number,
	/**  Number of commits the local branch is behind upstream. */
	behind: number,
	/**  The upstream reference (e.g. "origin/main"). */
	upstream: string,
} | null, AppError>(__TAURI_INVOKE("get_tracking_status", { repoPath })),
	/**
	 *  Return the ahead/behind status of the current branch relative to a specific remote.
	 *  Returns None if the branch does not exist on that remote (i.e. not published).
	 */
	getRemoteBranchStatus: (repoPath: string, remote: string) => typedError<{
	/**  Number of commits the local branch is ahead of upstream. */
	ahead: number,
	/**  Number of commits the local branch is behind upstream. */
	behind: number,
	/**  The upstream reference (e.g. "origin/main"). */
	upstream: string,
} | null, AppError>(__TAURI_INVOKE("get_remote_branch_status", { repoPath, remote })),
	/**  Push the current branch to the specified remote. */
	push: (repoPath: string, remote: string) => typedError<null, AppError>(__TAURI_INVOKE("push", { repoPath, remote })),
	/**  Publish the current branch to the specified remote (push with --set-upstream). */
	publishBranch: (repoPath: string, remote: string) => typedError<null, AppError>(__TAURI_INVOKE("publish_branch", { repoPath, remote })),
	/**  Pull from the specified remote into the current branch. */
	pull: (repoPath: string, remote: string) => typedError<null, AppError>(__TAURI_INVOKE("pull", { repoPath, remote })),
	/**  Fetch from the specified remote. */
	fetch: (repoPath: string, remote: string) => typedError<null, AppError>(__TAURI_INVOKE("fetch", { repoPath, remote })),
	/**
	 *  Cache an SSH passphrase so subsequent git remote operations can use it
	 *  via SSH_ASKPASS. The passphrase is held in-memory only.
	 */
	sshAddKey: (passphrase: string) => typedError<null, AppError>(__TAURI_INVOKE("ssh_add_key", { passphrase })),
	/**
	 *  Add a new remote with the given name and URL.
	 *  Validates the remote is reachable before completing.
	 */
	addRemote: (repoPath: string, name: string, url: string) => typedError<null, AppError>(__TAURI_INVOKE("add_remote", { repoPath, name, url })),
	/**  Remove an existing remote by name. */
	removeRemote: (repoPath: string, name: string) => typedError<null, AppError>(__TAURI_INVOKE("remove_remote", { repoPath, name })),
	/**  Return the persisted app state (repos, active tab, etc.). */
	getAppState: () => typedError<AppState, AppError>(__TAURI_INVOKE("get_app_state")),
	/**  Save the current app state to disk. */
	saveAppState: (state: AppState) => typedError<null, AppError>(__TAURI_INVOKE("save_app_state", { state })),
	/**  Check the status of the Linux desktop entry. */
	checkDesktopEntryStatus: () => typedError<DesktopEntryStatus, AppError>(__TAURI_INVOKE("check_desktop_entry_status")),
	/**  Register or update the Linux desktop entry. */
	registerDesktopEntry: () => typedError<null, AppError>(__TAURI_INVOKE("register_desktop_entry")),
	/**  Check whether a merge or revert is currently in progress. */
	checkMergeState: (repoPath: string) => typedError<MergeStateInfo, AppError>(__TAURI_INVOKE("check_merge_state", { repoPath })),
	/**  Merge the given branch into the current branch. */
	mergeBranch: (repoPath: string, branchName: string) => typedError<MergeResult, AppError>(__TAURI_INVOKE("merge_branch", { repoPath, branchName })),
	/**  Abort an in-progress merge. */
	mergeAbort: (repoPath: string) => typedError<null, AppError>(__TAURI_INVOKE("merge_abort", { repoPath })),
	/**  Return the current merge conflict state. */
	getMergeConflicts: (repoPath: string) => typedError<MergeConflictInfo, AppError>(__TAURI_INVOKE("get_merge_conflicts", { repoPath })),
	/**  Get per-file conflict counts. */
	getConflictCounts: (repoPath: string) => typedError<FileConflictInfo[], AppError>(__TAURI_INVOKE("get_conflict_counts", { repoPath })),
	/**  Resolve a conflicted file using the given strategy. */
	resolveConflict: (repoPath: string, filePath: string, resolution: ConflictResolution) => typedError<null, AppError>(__TAURI_INVOKE("resolve_conflict", { repoPath, filePath, resolution })),
	/**  Open a conflicted file in an external merge tool. */
	openInMergeTool: (repoPath: string, filePath: string, toolId: string) => typedError<null, AppError>(__TAURI_INVOKE("open_in_merge_tool", { repoPath, filePath, toolId })),
	/**
	 *  Finalize the merge after all conflicts are resolved.
	 *  Returns the number of commits merged.
	 */
	mergeContinue: (repoPath: string, message: string) => typedError<number, AppError>(__TAURI_INVOKE("merge_continue", { repoPath, message })),
	/**  Start watching a repository for file changes. */
	watchRepo: (repoPath: string) => typedError<null, AppError>(__TAURI_INVOKE("watch_repo", { repoPath })),
	/**  Stop watching a repository for file changes. */
	unwatchRepo: (repoPath: string) => typedError<null, AppError>(__TAURI_INVOKE("unwatch_repo", { repoPath })),
	/**  Revert the given commit. */
	revertCommit: (repoPath: string, hash: string) => typedError<RevertResult, AppError>(__TAURI_INVOKE("revert_commit", { repoPath, hash })),
	/**  Abort an in-progress revert. */
	revertAbort: (repoPath: string) => typedError<null, AppError>(__TAURI_INVOKE("revert_abort", { repoPath })),
	/**  Continue a revert after resolving conflicts. */
	revertContinue: (repoPath: string) => typedError<null, AppError>(__TAURI_INVOKE("revert_continue", { repoPath })),
	/**  Stash the currently staged changes with a message. */
	stashStaged: (repoPath: string, message: string) => typedError<null, AppError>(__TAURI_INVOKE("stash_staged", { repoPath, message })),
	/**  List all stash entries. */
	listStashes: (repoPath: string) => typedError<StashEntry[], AppError>(__TAURI_INVOKE("list_stashes", { repoPath })),
	/**  Apply a stash entry without removing it. */
	stashApply: (repoPath: string, index: number) => typedError<null, AppError>(__TAURI_INVOKE("stash_apply", { repoPath, index })),
	/**  Apply a stash entry and remove it. */
	stashPop: (repoPath: string, index: number) => typedError<null, AppError>(__TAURI_INVOKE("stash_pop", { repoPath, index })),
	/**  Drop a stash entry. */
	stashDrop: (repoPath: string, index: number) => typedError<null, AppError>(__TAURI_INVOKE("stash_drop", { repoPath, index })),
	/**  List files changed in a stash entry. */
	listStashFiles: (repoPath: string, index: number) => typedError<StatusEntry[], AppError>(__TAURI_INVOKE("list_stash_files", { repoPath, index })),
	/**  Get the diff for a single file in a stash entry. */
	diffStashFile: (repoPath: string, index: number, filePath: string) => typedError<FileDiff, AppError>(__TAURI_INVOKE("diff_stash_file", { repoPath, index, filePath })),
	/**  Get per-file stats for a stash entry. */
	stashFileStats: (repoPath: string, index: number) => typedError<FileStats[], AppError>(__TAURI_INVOKE("stash_file_stats", { repoPath, index })),
	/**  Get the contents of a file at a stash entry's revision. */
	showFileAtStash: (repoPath: string, index: number, filePath: string) => typedError<string, AppError>(__TAURI_INVOKE("show_file_at_stash", { repoPath, index, filePath })),
	/**
	 *  Tokenize the given file content for syntax highlighting.
	 *  Returns one array of tokens per line (split by `\n`).
	 * 
	 *  When `needed_lines` is provided, only those line indices get full token
	 *  detail; the rest receive a single plain token.  This dramatically
	 *  reduces work for large files where only a diff subset is displayed.
	 */
	tokenizeContent: (filePath: string, content: string, neededLines: number[] | null) => typedError<SyntaxToken[][], AppError>(__TAURI_INVOKE("tokenize_content", { filePath, content, neededLines })),
	/**  Return all merge tools currently available on the system. */
	getAvailableMergeTools: () => typedError<MergeToolInfo[], AppError>(__TAURI_INVOKE("get_available_merge_tools")),
	/**  Re-scan the system for available merge tools. */
	rescanMergeTools: () => typedError<MergeToolInfo[], AppError>(__TAURI_INVOKE("rescan_merge_tools")),
};

/* Types */
/**  Centralized error type for the application. */
export type AppError = ({ Git: string }) & { Io?: never; LockPoisoned?: never; Other?: never; SshAuthRequired?: never } | ({ Io: string }) & { Git?: never; LockPoisoned?: never; Other?: never; SshAuthRequired?: never } | ({ SshAuthRequired: string }) & { Git?: never; Io?: never; LockPoisoned?: never; Other?: never } | ({ LockPoisoned: string }) & { Git?: never; Io?: never; Other?: never; SshAuthRequired?: never } | ({ Other: string }) & { Git?: never; Io?: never; LockPoisoned?: never; SshAuthRequired?: never };

/**  Persisted application state (survives across app restarts). */
export type AppState = {
	/**  Paths of repositories that were open. */
	open_repos?: string[],
	/**  Index of the active tab. */
	active_index?: number,
	/**  Last-used parent folder for creating/cloning repositories. */
	last_parent_folder?: string | null,
	/**  Version the user chose to skip (won't be prompted again). */
	skipped_version?: string | null,
	/**  Release notes to show in "What's new" dialog on next startup. */
	pending_changelog?: string | null,
	/**  Version associated with the pending changelog. */
	pending_changelog_version?: string | null,
	/**  Whether the user dismissed the Linux desktop entry registration prompt. */
	dismiss_desktop_entry?: boolean,
	/**  Preferred UI theme. */
	theme?: string | null,
	/**  Preferred merge tool id. */
	preferred_merge_tool?: string | null,
};

/**  Information needed to decide how to handle branch deletion. */
export type BranchDeleteInfo = {
	/**  Whether the branch actually exists on the remote right now. */
	exists_on_remote: boolean,
	/**  The remote name (e.g. "origin"), if the branch is tracked. */
	remote_name: string | null,
	/**  The branch name on the remote (may differ from local name). */
	remote_branch_name: string | null,
};

/**  Data for rendering a branch graph. */
export type BranchGraphData = {
	/**  Commits in topological order (most recent first). */
	commits: GraphCommit[],
	/**  Names of the branches included in this graph. */
	branches: string[],
	/**  Commit hashes that exist only locally (not pushed to the selected remote). */
	local_only_commits: string[],
};

/**  A branch in the repository. */
export type BranchInfo = {
	/**  Branch name (e.g. "main"). */
	name: string,
	/**  Whether this is the currently checked-out branch. */
	is_current: boolean,
	/**  ISO 8601 timestamp of the most recent commit on this branch. */
	last_commit_date: string,
};

/**  How far ahead/behind the local branch is relative to its upstream. */
export type BranchTrackingStatus = {
	/**  Number of commits the local branch is ahead of upstream. */
	ahead: number,
	/**  Number of commits the local branch is behind upstream. */
	behind: number,
	/**  The upstream reference (e.g. "origin/main"). */
	upstream: string,
};

/**  A single recorded git CLI invocation. */
export type CommandEntry = {
	timestamp: string,
	command: string,
	cwd: string,
	exit_code: number,
	stdout: string,
	stderr: string,
	/**  How long the command took to execute, in milliseconds. */
	elapsed_ms: number,
	/**  Whether this command was a background/periodic operation (e.g. polling). */
	is_background: boolean,
};

/**  A single commit in the repository history. */
export type CommitInfo = {
	/**  Full commit hash. */
	hash: string,
	/**  Short (abbreviated) commit hash. */
	short_hash: string,
	/**  First line of the commit message. */
	summary: string,
	/**  Author name. */
	author: string,
	/**  ISO 8601 timestamp. */
	timestamp: string,
};

/**  How to resolve a conflicted file. */
export type ConflictResolution = 
/**  Accept the current branch's version (ours). */
"AcceptCurrent" | 
/**  Accept the incoming branch's version (theirs). */
"AcceptIncoming" | 
/**  Accept both changes (concatenate). */
"AcceptBoth";

/**  Status of the desktop entry relative to the running application. */
export type DesktopEntryStatus = 
/**  Not applicable on this platform. */
"NotApplicable" | 
/**  No desktop entry exists (user never registered or deleted it). */
"Missing" | 
/**  A desktop entry exists and the Exec path matches the running binary. */
"Current" | 
/**  A desktop entry exists but points to a different binary location. */
"Stale";

/**  Whether to diff staged (cached) or unstaged (worktree) changes. */
export type DiffArea = "Staged" | "Unstaged";

/**  A contiguous hunk of changes. */
export type DiffHunk = {
	/**  The hunk header (e.g. "@@ -1,3 +1,5 @@"). */
	header: string,
	/**  Starting line in the old file. */
	old_start: number,
	/**  Starting line in the new file. */
	new_start: number,
	/**  Lines in this hunk. */
	lines: DiffLine[],
};

/**  A single line within a diff hunk. */
export type DiffLine = {
	/**  The kind of change. */
	kind: DiffLineKind,
	/**  The line content (without the leading +/-/space). */
	content: string,
	/**  Line number in the old (a) side, if applicable. */
	old_lineno: number | null,
	/**  Line number in the new (b) side, if applicable. */
	new_lineno: number | null,
	/**
	 *  Inline change highlights within this line.
	 *  Empty when the entire line is added/deleted or for context lines.
	 */
	highlights: InlineHighlight[],
};

/**  The type of a line in a diff hunk. */
export type DiffLineKind = "Context" | "Addition" | "Deletion";

/**  Per-file conflict information including count of conflict markers. */
export type FileConflictInfo = {
	/**  The relative file path. */
	path: string,
	/**  Number of conflict regions (count of `<<<<<<<` markers). */
	conflict_count: number,
};

/**  The complete diff output for a single file. */
export type FileDiff = {
	/**  The relative path of the file. */
	path: string,
	/**  The hunks that make up this diff. */
	hunks: DiffHunk[],
};

/**  Per-file addition/deletion statistics from a diff. */
export type FileStats = {
	/**  Relative path of the file. */
	path: string,
	/**  Number of lines added. */
	additions: number,
	/**  Number of lines deleted. */
	deletions: number,
};

/**  The kind of change a file has undergone. */
export type FileStatus = "Added" | "Modified" | "Deleted" | "Renamed" | "Copied" | "Untracked" | "Unknown";

/**  A commit node in the branch graph visualization. */
export type GraphCommit = {
	/**  Full commit hash. */
	hash: string,
	/**  Short (abbreviated) commit hash. */
	short_hash: string,
	/**  First line of the commit message. */
	summary: string,
	/**  Author name. */
	author: string,
	/**  ISO 8601 timestamp. */
	timestamp: string,
	/**  Full hashes of parent commits. */
	parents: string[],
	/**  Branch/ref names pointing to this commit (e.g. "main", "origin/main"). */
	refs: string[],
	/**  Total lines added in this commit (if available). */
	insertions: number | null,
	/**  Total lines deleted in this commit (if available). */
	deletions: number | null,
};

/**  Describes the current HEAD position in VCS-agnostic terms. */
export type HeadState = {
	/**
	 *  The branch name relevant to the current state.
	 *  When `browsing_history` is false, this is the checked-out branch.
	 *  When `browsing_history` is true, this is the branch whose history
	 *  is being explored (best-effort; may be None if indeterminate).
	 */
	branch: string | null,
	/**
	 *  Whether the user is browsing history (checked out a specific commit
	 *  rather than being on a branch tip). The UI should disable mutating
	 *  operations like commit and sync when this is true.
	 */
	browsing_history: boolean,
};

/**  A highlighted span within a diff line, marking an inline change. */
export type InlineHighlight = {
	/**  Byte offset into the line content where the highlight starts. */
	start: number,
	/**  Length in bytes of the highlighted span. */
	length: number,
};

/**
 *  A selection of lines within a diff to stage/unstage.
 *  Each entry is (hunk_index, line_index_within_hunk).
 */
export type LineSelection = {
	hunk_index: number,
	line_index: number,
};

/**  Information about a merge conflict. */
export type MergeConflictInfo = {
	/**  The branch being merged into the current branch. */
	incoming_branch: string,
	/**  List of files with conflicts. */
	conflicted_files: string[],
};

/**  The result of a merge operation. */
export type MergeResult = 
/**
 *  Merge completed successfully (fast-forward or clean merge).
 *  Contains the number of commits that were merged.
 */
({ Success: {
	commits_merged: number,
} }) & { Conflict?: never } | 
/**  The branch was already up to date — nothing happened. */
"AlreadyUpToDate" | 
/**  Merge has conflicts that need to be resolved. */
({ Conflict: MergeConflictInfo }) & { Success?: never };

/**  The current merge/revert state of a repository. */
export type MergeStateInfo = 
/**  No merge or revert is in progress. */
"None" | 
/**  A merge is in progress with unresolved conflicts. */
({ Merging: {
	/**  The branch being merged in. */
	incoming_branch: string,
	/**  Number of files with conflicts. */
	conflict_count: number,
} }) & { Reverting?: never } | 
/**  A revert is in progress with unresolved conflicts. */
({ Reverting: {
	/**  Description (e.g. the commit being reverted). */
	incoming_branch: string,
	/**  Number of files with conflicts. */
	conflict_count: number,
} }) & { Merging?: never };

/**  Serializable merge tool info sent to the frontend. */
export type MergeToolInfo = {
	/**  Machine-readable identifier. */
	id: string,
	/**  Human-readable display name. */
	display_name: string,
	/**  Optional icon filename (e.g. "vscode.svg") served from `/icons/merge-tools/`. */
	icon: string | null,
};

/**  A branch that exists only on a remote (no local tracking branch). */
export type RemoteBranchInfo = {
	/**  Short branch name (e.g. "feature/cool-thing"), without the remote prefix. */
	name: string,
	/**  The remote it belongs to (e.g. "origin"). */
	remote: string,
	/**  ISO 8601 timestamp of the most recent commit on this branch. */
	last_commit_date: string,
};

/**  A configured remote for the repository. */
export type RemoteInfo = {
	/**  Remote name (e.g. "origin"). */
	name: string,
	/**  Remote URL. */
	url: string,
};

/**  Basic metadata about an opened repository. */
export type RepoInfo = {
	/**  Human-readable name (typically the folder name). */
	name: string,
	/**  Absolute path to the repository root. */
	path: string,
};

/**  The full working-tree status of a repository. */
export type RepoStatus = {
	/**  Files with staged (index) changes. */
	staged: StatusEntry[],
	/**  Files with unstaged (worktree) changes. */
	unstaged: StatusEntry[],
};

/**  Commit message fields restored after undoing the latest commit. */
export type RestoredCommitMessage = {
	/**  First line of the reverted commit message. */
	summary: string,
	/**  Remaining commit message body (without the summary line). */
	description: string,
};

/**  The result of a revert operation. */
export type RevertResult = 
/**  Revert completed successfully (no conflicts). */
"Success" | 
/**  Revert has conflicts that need to be resolved. */
{ Conflict: MergeConflictInfo };

/**  A single stash entry. */
export type StashEntry = {
	/**  The stash index (0, 1, 2, …). */
	index: number,
	/**  The stash ref (e.g. "stash@{0}"). */
	stash_ref: string,
	/**  The stash message. */
	message: string,
	/**  ISO 8601 timestamp. */
	timestamp: string,
	/**  Author name. */
	author: string,
	/**  The commit hash of the stash commit. */
	hash: string,
	/**  Short (abbreviated) commit hash. */
	short_hash: string,
};

/**  A changed file in the working tree or index. */
export type StatusEntry = {
	/**  Relative path of the file. */
	path: string,
	/**  Kind of change. */
	status: FileStatus,
};

/**
 *  A syntax token within a single line — carries only length and category.
 *  The frontend reconstructs the actual text content from the line string.
 */
export type SyntaxToken = {
	/**  Length of this token in characters (Unicode scalar values). */
	length: number,
	/**  Semantic category for theming. */
	category: TokenCategory,
};

/**  Semantic token category for frontend theming. */
export type TokenCategory = "keyword" | "string" | "comment" | "number" | "operator" | "function" | "type" | "variable" | "punctuation" | "tag" | "attribute" | "meta" | "plain";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

