mod commands;
mod error;

use commands::greet;

pub fn run() {
    // Work around WebKitGTK DMA-BUF crash on Wayland (protocol error 71).
    unsafe {
        #[cfg(target_os = "linux")]
        std::env::set_var("WEBKIT_DISABLE_DMABUF_RENDERER", "1");
    }

    let specta_builder = tauri_specta::Builder::<tauri::Wry>::new()
        .commands(tauri_specta::collect_commands![greet]);

    #[cfg(debug_assertions)]
    specta_builder
        .export(
            specta_typescript::Typescript::default()
                .header("// @ts-nocheck\n// This file was generated by specta. Do not edit."),
            "../src/ipc/bindings.ts",
        )
        .expect("Failed to export specta bindings");

    tauri::Builder::default()
        .invoke_handler(specta_builder.invoke_handler())
        .setup(move |app| {
            specta_builder.mount_events(app);
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
