pub mod command_log;
mod commands;
pub mod error;
pub mod state;
pub mod vcs;

use std::sync::Arc;

use command_log::CommandLog;
use commands::{
    check_path_exists, clone_repository, commit, create_branch, delete_branch,
    delete_remote_branch, fetch, get_app_state, get_branch_delete_info, get_branch_graph,
    get_command_log, get_commit_diff, get_commit_file_diff, get_commit_log, get_current_branch,
    get_file_at_commit, get_file_diff, get_status, get_tracking_status, init_repository,
    list_branches, list_commit_files, list_remotes, open_repository, publish_branch, pull, push,
    read_file_contents, save_app_state, stage_files, stage_lines, switch_branch, unstage_files,
    unstage_lines, validate_repo_path,
};
use state::AppStateManager;
use tauri::Manager;
use vcs::git::GitProvider;
use vcs::traits::VcsProvider;

pub fn run() {
    // Work around WebKitGTK DMA-BUF crash on Wayland (protocol error 71).
    #[cfg(target_os = "linux")]
    unsafe {
        std::env::set_var("WEBKIT_DISABLE_DMABUF_RENDERER", "1");
    }

    let specta_builder =
        tauri_specta::Builder::<tauri::Wry>::new().commands(tauri_specta::collect_commands![
            open_repository,
            init_repository,
            clone_repository,
            check_path_exists,
            validate_repo_path,
            get_command_log,
            get_current_branch,
            get_commit_log,
            get_commit_diff,
            get_commit_file_diff,
            get_file_at_commit,
            list_commit_files,
            list_branches,
            switch_branch,
            create_branch,
            delete_branch,
            delete_remote_branch,
            get_branch_delete_info,
            get_branch_graph,
            get_status,
            commit,
            stage_files,
            stage_lines,
            unstage_files,
            unstage_lines,
            read_file_contents,
            get_file_diff,
            list_remotes,
            get_tracking_status,
            push,
            publish_branch,
            pull,
            fetch,
            get_app_state,
            save_app_state,
        ]);

    #[cfg(debug_assertions)]
    specta_builder
        .export(
            specta_typescript::Typescript::default()
                .header("// @ts-nocheck\n// This file was generated by specta. Do not edit."),
            "../src/ipc/bindings.ts",
        )
        .expect("Failed to export specta bindings");

    let log = CommandLog::new(2000);
    let provider: Arc<dyn VcsProvider> = Arc::new(GitProvider::new(log.clone()));

    tauri::Builder::default()
        .plugin(tauri_plugin_updater::Builder::new().build())
        .plugin(tauri_plugin_dialog::init())
        .manage(log.clone())
        .manage(provider)
        .invoke_handler(specta_builder.invoke_handler())
        .setup(move |app| {
            log.set_app_handle(app.handle().clone());
            let state_manager = AppStateManager::new(app.handle());
            app.manage(state_manager);
            specta_builder.mount_events(app);
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
