pub mod command_log;
mod commands;
pub mod desktop_entry;
pub mod error;
pub mod merge_tools;
pub mod state;
pub mod syntax;
pub mod vcs;
pub mod watcher;

use std::sync::Arc;

use command_log::CommandLog;
use commands::{
    add_remote, check_desktop_entry_status, check_path_exists, checkout_commit, clone_repository, commit,
    create_branch, cherry_pick_commits, delete_branch, delete_remote_branch, diff_stash_file, discard_lines,
    discard_staged_files, discard_unstaged_files, fetch, get_app_state, get_branch_delete_info,
    get_branch_graph, get_command_log, get_commit_diff, get_commit_file_diff,
    get_commit_file_stats, get_commit_log, get_current_branch, get_diff_stats,
    get_file_at_commit, get_file_diff, get_head_state, get_merge_conflicts, get_conflict_counts,
    get_remote_branch_status, get_status, get_tracking_status, init_repository, list_branches,
    list_commit_files, list_remote_branches, list_remotes, list_stash_files, list_stashes, check_merge_state, merge_abort, merge_branch,
    merge_continue, open_in_merge_tool, open_repository, publish_branch, pull, push,
    read_file_contents, register_desktop_entry, remove_remote, resolve_conflict, revert_abort, revert_commit,
    revert_continue, save_app_state, show_file_at_stash, ssh_add_key, stage_files, stage_lines,
    tokenize_content,
    stash_apply, stash_drop, stash_file_stats, stash_pop, stash_staged, switch_branch,
    undo_last_commit, unstage_files, unstage_lines, validate_repo_path, watch_repo, unwatch_repo,
    get_available_merge_tools, rescan_merge_tools,
};
use merge_tools::MergeToolRegistry;
use state::AppStateManager;
use tauri::Manager;
use vcs::git::GitProvider;
use vcs::traits::VcsProvider;
use watcher::RepoWatcherManager;

pub fn run() {
    // Work around WebKitGTK DMA-BUF crash on Wayland (protocol error 71).
    #[cfg(target_os = "linux")]
    unsafe {
        std::env::set_var("WEBKIT_DISABLE_DMABUF_RENDERER", "1");
    }

    let specta_builder =
        tauri_specta::Builder::<tauri::Wry>::new().commands(tauri_specta::collect_commands![
            open_repository,
            init_repository,
            clone_repository,
            check_path_exists,
            validate_repo_path,
            get_command_log,
            get_current_branch,
            get_head_state,
            checkout_commit,
            get_commit_log,
            get_commit_diff,
            get_commit_file_diff,
            get_file_at_commit,
            list_commit_files,
            list_branches,
            list_remote_branches,
            switch_branch,
            create_branch,
            cherry_pick_commits,
            delete_branch,
            delete_remote_branch,
            get_branch_delete_info,
            get_branch_graph,
            get_status,
            commit,
            undo_last_commit,
            stage_files,
            stage_lines,
            unstage_files,
            unstage_lines,
            discard_unstaged_files,
            discard_staged_files,
            discard_lines,
            read_file_contents,
            get_file_diff,
            get_diff_stats,
            get_commit_file_stats,
            list_remotes,
            get_tracking_status,
            get_remote_branch_status,
            push,
            publish_branch,
            pull,
            fetch,
            ssh_add_key,
            add_remote,
            remove_remote,
            get_app_state,
            save_app_state,
            check_desktop_entry_status,
            register_desktop_entry,
            check_merge_state,
            merge_branch,
            merge_abort,
            get_merge_conflicts,
            get_conflict_counts,
            resolve_conflict,
            open_in_merge_tool,
            merge_continue,
            watch_repo,
            unwatch_repo,
            revert_commit,
            revert_abort,
            revert_continue,
            stash_staged,
            list_stashes,
            stash_apply,
            stash_pop,
            stash_drop,
            list_stash_files,
            diff_stash_file,
            stash_file_stats,
            show_file_at_stash,
            tokenize_content,
            get_available_merge_tools,
            rescan_merge_tools,
        ]);

    #[cfg(debug_assertions)]
    specta_builder
        .export(
            specta_typescript::Typescript::default()
                .header("// @ts-nocheck\n// This file was generated by specta. Do not edit."),
            "../src/ipc/bindings.ts",
        )
        .expect("Failed to export specta bindings");

    let log = CommandLog::new(2000);
    let provider: Arc<dyn VcsProvider> = Arc::new(GitProvider::new(log.clone()));
    let highlighter = Arc::new(syntax::SyntaxHighlighter::new());
    let merge_tool_registry = Arc::new(MergeToolRegistry::new());

    tauri::Builder::default()
        .plugin(tauri_plugin_updater::Builder::new().build())
        .plugin(tauri_plugin_process::init())
        .plugin(tauri_plugin_dialog::init())
        .manage(log.clone())
        .manage(provider)
        .manage(highlighter)
        .manage(merge_tool_registry)
        .manage(Arc::new(RepoWatcherManager::new()))
        .invoke_handler(specta_builder.invoke_handler())
        .setup(move |app| {
            if let Err(e) = log.set_app_handle(app.handle().clone()) {
                eprintln!("Failed to set app handle in command log: {}", e);
            }
            let state_manager = AppStateManager::new(app.handle());
            app.manage(state_manager);
            specta_builder.mount_events(app);
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
