name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
      release_notes:
        required: true

jobs:
  release:
    permissions:
      contents: write

    strategy:
      matrix:
        platform:
          - ubuntu-22.04
          - windows-latest
          - macos-latest

    runs-on: ${{ matrix.platform }}

    environment: Deployment

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: pnpm/action-setup@v4
        with:
          version: latest

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install cargo-edit
        run: cargo install cargo-edit

      - name: Update version temporarily
        run: |
          cd src-tauri
          cargo set-version ${{ github.event.inputs.version }}
          cd ..

      - name: Install frontend dependencies
        run: pnpm install

      - name: Linux dependencies
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt update
          sudo apt install -y \
            libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libxdo-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: v${{ github.event.inputs.version }}
          releaseName: v${{ github.event.inputs.version }}
          releaseBody: ${{ github.event.inputs.release_notes }}
          releaseDraft: false
          prerelease: false